language: ruby
rvm:
  #- 1.8.7
  - 1.9.3
  - 2.1.1
  - 2.2.2
  - jruby-19mode
  #- jruby-20mode
script: bundle exec rspec
branches:
  only:
    - master
  #except:
  #  - master

sudo: false
cache: bundler

